### ISSUE TITLE
Commas don't appear

### ISSUE THREAD

**Issue by ayamahmod** [kyper-data/python-highcharts#4]
Why commas don't appear as thousands separator in the output file?
![screenshot from 2016-03-23 15 38 26](https://cloud.githubusercontent.com/assets/11185678/13986894/7bbb5eca-f10d-11e5-9d72-22901ea7089e.png)

**Comment by flyjohn02** [comment]
Hi Aya,

I just added the capability to include two options: global and lang (in [Highchart.setOptions](http://api.highcharts.com/highcharts#lang.thousandsSep)). We did not add those intentionally because we were not sure how useful they could be and if they are duplicated setting for other purposes. However, it seems like there are something set only by these two.

You can use these two as other options by set_option/set_dict_options method. To add commas, you need to set thousandsSep in lang. You can check this [discussion](http://stackoverflow.com/questions/29209491/highcharts-format-all-numbers-with-comma) for how to construct the option.

Also, I hope you can understand that python-highchart is an open source project and relies on your participation and contribution. We (Kyle and I) have no association with highcharts. The only purpose here is to make contribution to the society and help each other. Hopefully, we can attract more people to use highchart and (even more) to the data analysis and visualization community. We are happy to help but cannot promise to solve any specific question in the plot someone likes to make. 

Thanks,

Hank
