### ISSUE TITLE
Heatmap colorAxis

### ISSUE THREAD

**Issue by rawanramzy** [kyper-data/python-highcharts#6]
I found the heatmap in the highcharts_types.py, I'm trying to plot a heatmap like [this](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/heatmap/), but I get KeyError: colorAxis. What should I do?
![heatmaperror](https://cloud.githubusercontent.com/assets/18486027/14565681/7fdb3986-032c-11e6-9412-51314a8c6029.PNG)

**Comment by flyjohn02** [comment]
Hi,

The problem is that colorAxis actually does not include in highcharts but highmaps: http://api.highcharts.com/highcharts. I just include highmaps in highcharts source and added colorAxis option such that you can use it. 

I tried it and it works:
![chart](https://cloud.githubusercontent.com/assets/11906148/14764580/04408d20-098b-11e6-8c64-f1a5dbbb04f2.jpeg)

Please pull the latest python-highcharts code and feel free that let me know if you still get the problem.

Hank

**Comment by rawanramzy** [comment]
It works finally! 
Thank you a lot. I really love this framework, and appreciate your work a lot.

**Comment by ayamahmod** [comment]
@flyjohn02 after this update, the colorscale always appear even when it's 2D plotting, and the cooraxis isn't initialized  
![colorscale](https://cloud.githubusercontent.com/assets/11185678/16382332/ab1e32fa-3c80-11e6-99df-85e814fc697f.PNG)
